
package com.becas.uniluyten;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SolicitudBecaImpService", targetNamespace = "http://uniluyten.becas.com/", wsdlLocation = "http://localhost:8080/modulo-solicitud-becas/SolicitudBeca?wsdl")
public class SolicitudBecaImpService
    extends Service
{

    private final static URL SOLICITUDBECAIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOLICITUDBECAIMPSERVICE_EXCEPTION;
    private final static QName SOLICITUDBECAIMPSERVICE_QNAME = new QName("http://uniluyten.becas.com/", "SolicitudBecaImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/modulo-solicitud-becas/SolicitudBeca?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOLICITUDBECAIMPSERVICE_WSDL_LOCATION = url;
        SOLICITUDBECAIMPSERVICE_EXCEPTION = e;
    }

    public SolicitudBecaImpService() {
        super(__getWsdlLocation(), SOLICITUDBECAIMPSERVICE_QNAME);
    }

    public SolicitudBecaImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOLICITUDBECAIMPSERVICE_QNAME, features);
    }

    public SolicitudBecaImpService(URL wsdlLocation) {
        super(wsdlLocation, SOLICITUDBECAIMPSERVICE_QNAME);
    }

    public SolicitudBecaImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOLICITUDBECAIMPSERVICE_QNAME, features);
    }

    public SolicitudBecaImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SolicitudBecaImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SolicitudBeca
     */
    @WebEndpoint(name = "SolicitudBecaImpPort")
    public SolicitudBeca getSolicitudBecaImpPort() {
        return super.getPort(new QName("http://uniluyten.becas.com/", "SolicitudBecaImpPort"), SolicitudBeca.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SolicitudBeca
     */
    @WebEndpoint(name = "SolicitudBecaImpPort")
    public SolicitudBeca getSolicitudBecaImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://uniluyten.becas.com/", "SolicitudBecaImpPort"), SolicitudBeca.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOLICITUDBECAIMPSERVICE_EXCEPTION!= null) {
            throw SOLICITUDBECAIMPSERVICE_EXCEPTION;
        }
        return SOLICITUDBECAIMPSERVICE_WSDL_LOCATION;
    }

}
