
package com.becas.uniluyten;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SolicitudBeca", targetNamespace = "http://uniluyten.becas.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SolicitudBeca {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.becas.uniluyten.Solicitud
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "solicitarBeca", targetNamespace = "http://uniluyten.becas.com/", className = "com.becas.uniluyten.SolicitarBeca")
    @ResponseWrapper(localName = "solicitarBecaResponse", targetNamespace = "http://uniluyten.becas.com/", className = "com.becas.uniluyten.SolicitarBecaResponse")
    public Solicitud solicitarBeca(
        @WebParam(name = "arg0", targetNamespace = "")
        Solicitud arg0);

}
